name: Infrastructure Website Pipeline - DEV
on:
  push:
    branches:
    - main
    paths:
    - 'infrastructure/website/**'
  pull_request:
    branches:
    - main
    paths:
    - 'infrastructure/website/**'

jobs:
  perform_deployment:
    uses: CodeWell-fi/website/.github/workflows/infrastructure.yml
    with:
      environment: dev
    secrets:
      azure_pipeline_config: ${{ secrets.AZURE_PIPELINE_CONFIG_DEV }} # Value of this GH secret is originally got from Azure KV secret created by bootstrap pipeline
      secret_tenant_id: ${{ secrets.SECRET_TENANT_ID }}
      secret_subscription_id: ${{ secrets.SECRET_SUBSCRIPTION_ID }}
