name: Infrastructure Website Pipeline - PROD
on: workflow_dispatch # Only manually executed

jobs:
  perform_deployment:
    uses: CodeWell-fi/website/.github/workflows/infrastructure.yml@main
    with:
      environment: prod
      github_event_to_proceed_to_apply: workflow_dispatch
      required_branch: main
      upload_code_coverage: false
    secrets:
      azure_pipeline_config: ${{ secrets.AZURE_PIPELINE_CONFIG_PROD }} # Value of this GH secret is originally got from Azure KV secret created by bootstrap pipeline
      secret_tenant_id: ${{ secrets.SECRET_TENANT_ID }}
      secret_subscription_id: ${{ secrets.SECRET_SUBSCRIPTION_ID }}
