name: Website CD Pipeline - DEV
on:
  workflow_run:
    workflows: [ "Website CI Pipeline" ]
    branches: [ main ]
    types: [ completed ]

defaults:
  run:
    shell: bash
    working-directory: frontend/publish
env:
  WEBSITE_ENV: dev
  AZURE_PIPELINE_CONFIG: ${{ secrets.AZURE_PIPELINE_CONFIG_DEV }} # Value of this GH secret is originally got from Azure KV secret created by bootstrap pipeline, and is superset of schema defined in website/src/config.ts file
  ONLY_TO_MASK_OUTPUT_TENANT_ID: ${{ secrets.SECRET_TENANT_ID }}
  ONLY_TO_MASK_OUTPUT_SUBSCRIPTION_ID: ${{ secrets.SECRET_SUBSCRIPTION_ID }}

jobs:
  perform-cd:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1 # No need to get full history
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - uses: dawidd6/action-download-artifact@v2
        name: Download build artifact
        with:
          workflow: website-ci.yml
          run_id: ${{ github.event.workflow_run.id }}
          name: site-contents
          path: website/build
      - id: preview
        name: Deploy website
        run: |
          set -e

          npm ci --ignore-scripts
          cp ../../infrastructure/website/src/naming.ts src
          export WEBSITE_INFRA_CONFIG="$(cat "config/config-${WEBSITE_ENV}.json")"
          npm run deploy