name: Website CI Pipeline
on:
  push:
    branches:
    - main
    paths:
    - 'frontend/code/**'
  pull_request:
    branches:
    - main
    paths:
    - 'frontend/code/**'

defaults:
  run:
    shell: bash

env:
  SKIP_PREFLIGHT_CHECK: "true"
  CONTACT_EMAIL_ADDRESS: ${{ secrets.CONTACT_EMAIL_ADDRESS }}

jobs:
  build_and_test:
    name: Build and test website
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1 # No need to get full history
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - id: preview
        name: Build and test website
        run: |
          set -e
          ./.github/website-ci.sh
      # Artifact will be used by CD pipeline - but only upload it when not doing PR run
      - uses: actions/upload-artifact@v2
        if: ${{ github.event_name == 'push' }}
        with:
          name: site-contents
          path: frontend/code/build/
      - uses: codecov/codecov-action@v1
        with:
          flags: frontend-code
          directory: frontend/code
      